import Foundation

enum AppStrings {
    static func text(_ key: String, language: AppLanguage) -> String {
        dictionaries[language]?[key] ?? english[key] ?? key
    }

    static func format(_ key: String, language: AppLanguage, arguments: [CVarArg]) -> String {
        let format = text(key, language: language)
        return String(
            format: format,
            locale: Locale(identifier: language.localeIdentifier),
            arguments: arguments
        )
    }

    static func currentText(_ key: String) -> String {
        text(key, language: AppLanguage.stored)
    }

    static func currentFormat(_ key: String, arguments: [CVarArg]) -> String {
        format(key, language: AppLanguage.stored, arguments: arguments)
    }

    private static let dictionaries: [AppLanguage: [String: String]] = [
        .english: english,
        .czech: czech,
    ]

    private static let english: [String: String] = [
        "app.name": "SlateCue",
        "app.subtitle": "Offline ADR and dubbing cue reader for macOS.",
        "window.display": "Display",
        "section.preparation": "Preparation",
        "section.recording": "Recording",
        "command.import_xlsx": "Import XLSX…",
        "command.open_project": "Open Project…",
        "command.save_project": "Save Project",
        "command.save_project_as": "Save Project As…",
        "command.export_xlsx": "Export XLSX…",
        "toolbar.import": "Import",
        "toolbar.open": "Open",
        "toolbar.save": "Save",
        "toolbar.display": "Display",
        "toolbar.export": "Export",
        "alert.error_title": "Error",
        "common.ok": "OK",
        "common.add": "Add",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.unassigned": "Unassigned",
        "common.empty_cue": "(empty cue)",
        "common.cue_count": "%d cues",
        "common.cue_index": "Active cue #%d",
        "welcome.load_demo": "Load Demo",
        "preparation.new_actor_placeholder": "New actor",
        "preparation.character": "Character",
        "preparation.actor": "Actor",
        "preparation.cues": "Cues",
        "preparation.words": "Words",
        "preparation.takes_div8": "/8",
        "preparation.recorded": "Recorded",
        "preparation.remaining": "Remaining",
        "recording.active_actor": "Active actor",
        "recording.no_actor_marking": "No actor marking",
        "recording.character": "Character",
        "recording.all_characters": "All characters",
        "recording.only_unrecorded": "Only unrecorded",
        "recording.hide_tc_frames": "Hide TC frames",
        "recording.display_context": "Display +/- %d",
        "recording.marked_for_actor": "Marked for %@: %d",
        "recording.previous": "Previous",
        "recording.record": "Record / Enter",
        "recording.revert": "Revert",
        "recording.next": "Next",
        "recording.edit": "Edit / E",
        "recording.selected_line": "Selected line",
        "recording.quick_edit": "Quick Edit",
        "recording.restore_original_text": "Restore original text",
        "recording.original": "Original",
        "recording.edited_line": "Edited line",
        "recording.edit_placeholder": "Edit the selected line",
        "recording.enter_saves_escape_cancels": "Enter saves, Esc cancels.",
        "recording.status_header": "Status",
        "recording.source_header": "SOURCE",
        "recording.character_header": "Character",
        "recording.actor_header": "Actor",
        "recording.timecode_header": "IN-TC",
        "recording.text_header": "Text",
        "recording.status.recorded": "recorded",
        "recording.status.selected": "selected",
        "recording.status.waiting": "waiting",
        "recording.badge.edited": "edited",
        "recording.hint.editing": "You are editing the selected cue. Enter saves it, Esc cancels.",
        "recording.hint.select_actor": "Select an active actor before recording.",
        "recording.hint.none_left": "There are no unrecorded cues left for the active actor.",
        "recording.hint.jump_next": "Enter will jump to the next marked cue for the active actor.",
        "recording.hint.other_actor": "The current cue does not belong to the active actor. Enter will jump to the next marked cue.",
        "recording.hint.already_recorded": "The current cue is already recorded. Enter will jump to the next marked cue.",
        "display.no_selected_cue": "No cue is currently selected",
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.language_help": "Switch the app UI between English and Czech.",
        "language.english": "English",
        "language.czech": "Čeština",
        "panel.import_xlsx.title": "Import XLSX",
        "panel.import_xlsx.prompt": "Import",
        "panel.open_project.title": "Open Project",
        "panel.open_project.prompt": "Open",
        "panel.save_project.title": "Save Project",
        "panel.save_project.prompt": "Save",
        "panel.export_xlsx.title": "Export XLSX",
        "panel.export_xlsx.prompt": "Export",
        "alert.select_actor_first": "Select an active actor first.",
        "error.missing_manifest": "The project package does not contain manifest.json.",
        "error.xlsx_missing_dialogue_sheet": "The XLSX file is missing the Dialogue List sheet.",
        "error.xlsx_unreadable_workbook": "The XLSX workbook structure could not be read.",
        "error.command_failed_without_output": "%@ exited with status %d.",
        "error.command_failed_with_output": "%@ exited with status %d: %@",
        "demo.project_name": "Demo Project",
    ]

    private static let czech: [String: String] = [
        "app.name": "SlateCue",
        "app.subtitle": "Offline čtečka pro režijní cueing dabingu na macOS.",
        "window.display": "Display",
        "section.preparation": "Přípravy",
        "section.recording": "Nahrávání",
        "command.import_xlsx": "Importovat XLSX…",
        "command.open_project": "Otevřít projekt…",
        "command.save_project": "Uložit projekt",
        "command.save_project_as": "Uložit projekt jako…",
        "command.export_xlsx": "Exportovat XLSX…",
        "toolbar.import": "Import",
        "toolbar.open": "Otevřít",
        "toolbar.save": "Uložit",
        "toolbar.display": "Display",
        "toolbar.export": "Export",
        "alert.error_title": "Chyba",
        "common.ok": "OK",
        "common.add": "Přidat",
        "common.cancel": "Zrušit",
        "common.save": "Uložit",
        "common.unassigned": "Nepřiřazeno",
        "common.empty_cue": "(prázdný vstup)",
        "common.cue_count": "%d cue",
        "common.cue_index": "Aktivní cue #%d",
        "welcome.load_demo": "Načíst demo",
        "preparation.new_actor_placeholder": "Nový dabér",
        "preparation.character": "Postava",
        "preparation.actor": "Dabér",
        "preparation.cues": "Vstupy",
        "preparation.words": "Slova",
        "preparation.takes_div8": "/8",
        "preparation.recorded": "Nahráno",
        "preparation.remaining": "Zbývá",
        "recording.active_actor": "Aktivní dabér",
        "recording.no_actor_marking": "Bez označení dabéra",
        "recording.character": "Postava",
        "recording.all_characters": "Všechny postavy",
        "recording.only_unrecorded": "Jen nenahrané",
        "recording.hide_tc_frames": "Skrýt FPS v TC",
        "recording.display_context": "Display +/- %d",
        "recording.marked_for_actor": "Označeno pro %@: %d",
        "recording.previous": "Předchozí",
        "recording.record": "Nahrát / Enter",
        "recording.revert": "Vrátit",
        "recording.next": "Další",
        "recording.edit": "Upravit / E",
        "recording.selected_line": "Vybraná replika",
        "recording.quick_edit": "Quick Edit",
        "recording.restore_original_text": "Původní text",
        "recording.original": "Původní",
        "recording.edited_line": "Upravená replika",
        "recording.edit_placeholder": "Uprav repliku",
        "recording.enter_saves_escape_cancels": "Enter uloží, Esc zruší.",
        "recording.status_header": "Stav",
        "recording.source_header": "SOURCE",
        "recording.character_header": "Postava",
        "recording.actor_header": "Dabér",
        "recording.timecode_header": "IN-TC",
        "recording.text_header": "Text",
        "recording.status.recorded": "nahraný",
        "recording.status.selected": "vybraný",
        "recording.status.waiting": "čeká",
        "recording.badge.edited": "upraveno",
        "recording.hint.editing": "Edituješ vybraný cue. Enter uloží úpravu, Esc ji zruší.",
        "recording.hint.select_actor": "Vyber aktivního dabéra, jinak se cue nenahraje.",
        "recording.hint.none_left": "Pro aktivního dabéra už není žádný nenahraný cue.",
        "recording.hint.jump_next": "Enter skočí na další označený cue aktivního dabéra.",
        "recording.hint.other_actor": "Aktuální cue nepatří aktivnímu dabérovi. Enter skočí na další označený cue.",
        "recording.hint.already_recorded": "Aktuální cue už je nahraný. Enter skočí na další označený cue.",
        "display.no_selected_cue": "Není vybraný žádný cue",
        "settings.title": "Nastavení",
        "settings.language": "Jazyk",
        "settings.language_help": "Přepíná jazyk uživatelského rozhraní mezi angličtinou a češtinou.",
        "language.english": "English",
        "language.czech": "Čeština",
        "panel.import_xlsx.title": "Import XLSX",
        "panel.import_xlsx.prompt": "Importovat",
        "panel.open_project.title": "Otevřít projekt",
        "panel.open_project.prompt": "Otevřít",
        "panel.save_project.title": "Uložit projekt",
        "panel.save_project.prompt": "Uložit",
        "panel.export_xlsx.title": "Export XLSX",
        "panel.export_xlsx.prompt": "Exportovat",
        "alert.select_actor_first": "Nejdřív vyber aktivního dabéra.",
        "error.missing_manifest": "Projekt neobsahuje manifest.json.",
        "error.xlsx_missing_dialogue_sheet": "V XLSX chybí list Dialogue List.",
        "error.xlsx_unreadable_workbook": "Nepodařilo se načíst strukturu XLSX.",
        "error.command_failed_without_output": "%@ skončil s chybou %d.",
        "error.command_failed_with_output": "%@ skončil s chybou %d: %@",
        "demo.project_name": "Demo projekt",
    ]
}
